version: "3.3"

x-user: &user
  user: 1000:1000 # default
 
x-environment: &environment
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Guayaquil

x-policy: &policy
  restart: unless-stopped

x-security: &security
  security_opt:
    - no-new-privileges:true

x-network: &network
  networks:
    - home-network

networks:
  home-network:
    driver: bridge
  my-network:

services:
  yacht:
    image: selfhostedpro/yacht
    container_name: yacht
    ports:
      - 9004:8000
    volumes:
      - ${SERVER_DATA_DIR}/yacht/config:/config
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    <<: *environment
    <<: *network 
    <<: *policy 
    labels:
      - homepage.group=Admin
      - homepage.name=Yacht
      - homepage.container=yacht
      - homepage.server=my-docker
      - homepage.description=Docker Administration
      - homepage.href=http://${IP_ADDRESS_G}:9004
      - com.centurylinklabs.watchtower.enable=true

  changedetection:
    image: lscr.io/linuxserver/changedetection.io:latest
    container_name: changedetection
    <<: *environment 
    <<: *policy 
    <<: *network 
    volumes:
      - ${SERVER_DATA_DIR}/changedetection/config:/config
    ports:
      - 8010:5000
    labels:
      - homepage.group=Utils
      - homepage.name=ChangeDetection
      - homepage.container=changedetection
      - homepage.server=my-docker
      - homepage.description=Check Changes in Websites
      - homepage.href=http://${IP_ADDRESS_G}:8010
      - com.centurylinklabs.watchtower.enable=true

  kuma:
    container_name: kuma
    image: louislam/uptime-kuma:1
    <<: *environment 
    <<: *policy 
    <<: *network 
    volumes:
      -  ${SERVER_DATA_DIR}/uptime-kuma/config:/app/data
    ports:
      - "8005:3001"
    labels:
      - homepage.group=Utils
      - homepage.name=Kuma
      - homepage.container=kuma
      - homepage.server=my-docker
      - homepage.description=Check Status in Web Pages
      - homepage.href=http://${IP_ADDRESS_G}:8005
      - com.centurylinklabs.watchtower.enable=true