version: "3.3"

x-user: &user
  user: 1000:1000 # default
 
x-environment: &environment
  environment:
    # - INIT_ASSETS=0 # default
    - PUID=1000
    - PGID=1000
    - TZ=America/Guayaquil
    # - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
    # - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional

x-policy: &policy
    restart: unless-stopped

x-security: &security
    security_opt:
      - no-new-privileges:true

services:
  local:
    image: b4bz/homer
    container_name: local
    <<: *user 
    <<: *environment 
    <<: *policy 
    ports:
      - 80:8080
    volumes:
      - ${REPO_CONFIG_DIR}/assets:/www/assets


# Streaming

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    <<: *environment
    <<: *policy
    # labels:
    #   plugsy.name: "bazarr"
    #   plugsy.parents: "Todo"
    #   plugsy.icon: "@styled-icons/feather/Server"
    volumes:
      - ${SERVER_DATA_DIR}/bazarr/config:/config
      - ${SERVER_STORAGE_DIR}/movies:/movies #optional
      - ${SERVER_STORAGE_DIR}/tv:/tv #optional
    ports:
      - 6001:6767

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    <<: *environment
    <<: *policy
    <<: *security
    volumes:
      - ${SERVER_DATA_DIR}/overseerr/config:/config
      - ${SERVER_STORAGE_DIR}/movies:/movies #optional
      - ${SERVER_STORAGE_DIR}/downloads:/downloads #optional
    ports:
      - 6002:7878

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    <<: *environment
    <<: *policy

    volumes:
      - ${SERVER_DATA_DIR}/sonarr/config:/config
      - ${SERVER_STORAGE_DIR}/tv:/tv #optional
      - ${SERVER_STORAGE_DIR}/downloads:/downloads #optional
    ports:
      - 6003:8989

# Indexers

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
    <<: *environment
    <<: *policy
    <<: *security

    volumes:
      -  ${SERVER_DATA_DIR}/prowlarr/config:/config
    ports:
      - 7001:9696
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    <<: *environment 
    <<: *policy

    volumes:
      - ${SERVER_DATA_DIR}/transmission/config:/config
      - ${SERVER_STORAGE_DIR}/downloads:/downloads
      - ${SERVER_STORAGE_DIR}/watch:/watch
    ports:
      - 7003:9091
      - 51413:51413
      - 51413:51413/udp
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    <<: *environment
    <<: *policy
    volumes:
      - ${SERVER_DATA_DIR}/tautulli/config:/config
    ports:
      - 7004:8181

  flexget:
    image: wiserain/flexget
    container_name: flexget
    <<: *environment
    <<: *policy
    restart: on-failure:5
    ports :
      - 5050:5050
    environment:
      - FG_WEBUI_PASSWD=holiComoEstas
      - TORRENT_PLUGIN=transmission
    volumes:
      - ${SERVER_STORAGE_DIR}/downloads:/data
      # - ${SERVER_DATA_DIR}/flexget/config:/config
      - ${REPO_CONFIG_DIR}/assets/flexget:/config


# Utils

  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    <<: *environment 
    <<: *policy
    <<: *security
    ports:
      - 8001:80
    volumes:
      - ${SERVER_STORAGE_DIR}:/srv
      - ${REPO_CONFIG_DIR}/assets/settings.json:/config/settings.json
      - ${REPO_CONFIG_DIR}/assets/filebrowser.db:/database/filebrowser.db

  ubooquity:
    image: lscr.io/linuxserver/ubooquity:latest
    container_name: ubooquity
    <<: *environment
    <<: *policy
    volumes:
      - ${SERVER_DATA_DIR}/ubooquity/config:/config
      - ${SERVER_STORAGE_DIR}/books:/books
      - ${SERVER_STORAGE_DIR}/comics:/comics
      - ${SERVER_STORAGE_DIR}:/files
    ports:
      - 8002:2202
      - 8003:2203

  # calibre-web:
  #   image:  ghcr.io/linuxserver/calibre-web
  #   container_name: calibre-web
  #   <<: *environment 
  #   <<: *policy
  #   environment:
  #     - DOCKER_MODS=ghcr.io/linuxserver/mods:universal-calibre  #optional
  #     - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
  #   ports:
  #     - 8004:8083

  #   volumes:
  #     - ${SERVER_DATA_DIR}/calibre-web/config:/config
  #     - ${SERVER_STORAGE_DIR}/mybooks:/books

  calibre:
    image:  lscr.io/linuxserver/calibre:latest
    container_name: calibre
    <<: *environment 
    <<: *policy
    ports:
      - 8004:8080
      - 8008:8081

    volumes:
      - ${SERVER_DATA_DIR}/calibre/config:/config
      - ${SERVER_STORAGE_DIR}/mybooks:/books

  kuma:
    container_name: kuma
    image: louislam/uptime-kuma:1
    <<: *environment 
    <<: *policy 
    volumes:
      -  ${SERVER_DATA_DIR}/uptime-kuma/config:/app/data
    ports:
      - "8005:3001"
  
  webtop:
    image: lscr.io/linuxserver/webtop:latest
    container_name: webtop
    <<: *environment 
    <<: *policy 
    volumes:
      - ${SERVER_DATA_DIR}/webtop/config:/config
    ports:
      - 8006:3000

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    <<: *environment 
    <<: *policy
    <<: *security
    volumes:
      - ${SERVER_DATA_DIR}/readarr/config:/config
      - ${SERVER_STORAGE_DIR}/books:/books
      - ${SERVER_STORAGE_DIR}/downloads:/downloads #optional
    ports:
      - 8007:8787
    restart: unless-stopped

# System

  whoami:
    image: containous/whoami:latest
    container_name: whoami
    <<: *user 
    <<: *environment 
    <<: *policy 
    ports:
      - 9001:80

  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    container_name: librespeed
    <<: *environment 
    <<: *policy 
    volumes:
      - ${SERVER_DATA_DIR}/librespeed/config:/config
    ports:
      - 9002:80

  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    <<: *environment 
    <<: *policy 
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3001:3000/tcp
      - 81:80/tcp
      - 443:443/tcp
    volumes:
      - ${SERVER_DATA_DIR}/adguardhome/work:/opt/adguardhome/work
      - ${SERVER_DATA_DIR}/adguardhome/config:/opt/adguardhome/conf

  castblock:
    network_mode: host
    image: erdnaxeli/castblock
    environment:
      - CATEGORIES=sponsor,selfpromo
