version: "3.3"

x-user: &user
  user: 1000:1000 # default
 
x-environment: &environment
  environment:
    # - INIT_ASSETS=0 # default
    - PUID=1000
    - PGID=1000
    - TZ=America/Guayaquil
    # - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
    # - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional

x-policy: &policy
    restart: unless-stopped

x-security: &security
    security_opt:
      - no-new-privileges:true

x-network: &network
    networks:
      - home-network
networks:
  home-network:
    driver: bridge

services:
  # local:
  #   image: b4bz/homer
  #   container_name: local
  #   <<: *user 
  #   <<: *environment 
  #   <<: *policy 
  #   <<: *network 

  #   ports:
  #     - 80:8080
  #   volumes:
  #     - ${REPO_CONFIG_DIR}/assets:/www/assets

  local:
    image: ghcr.io/benphelps/homepage:latest
    container_name: local
    <<: *user 
    <<: *environment 
    <<: *policy 
    <<: *network 

    ports:
      - 80:3000
    volumes:
      - ${REPO_CONFIG_DIR}/configs:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations


# Streaming

  # bazarr:
  #   image: lscr.io/linuxserver/bazarr:latest
  #   container_name: bazarr
  #   <<: *environment
  #   <<: *policy
  #   <<: *network 
  #   volumes:
  #     - ${SERVER_DATA_DIR}/bazarr/config:/config
  #     - ${SERVER_STORAGE_DIR}/movies:/movies #optional
  #     - ${SERVER_STORAGE_DIR}/tv:/tv #optional
  #   ports:
  #     - 6001:6767

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    <<: *environment
    <<: *policy
    <<: *security
    <<: *network 
    volumes:
      - ${SERVER_DATA_DIR}/overseerr/config:/config
      - ${SERVER_STORAGE_DIR}/movies:/movies #optional
      - ${SERVER_STORAGE_DIR}/downloads:/downloads #optional
    ports:
      - 6002:7878

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    <<: *environment
    <<: *policy
    <<: *network 

    volumes:
      - ${SERVER_DATA_DIR}/sonarr/config:/config
      - ${SERVER_STORAGE_DIR}/tv:/tv #optional
      - ${SERVER_STORAGE_DIR}/downloads:/downloads #optional
    ports:
      - 6003:8989

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    <<: *environment
    <<: *policy
    network_mode: 'host'
    ports:
      -  8096:8096/tcp
    volumes:
      - ${SERVER_DATA_DIR}/jellyfin/config:/config
      - ${SERVER_DATA_DIR}/jellyfin/cache:/cache
      - ${SERVER_STORAGE_DIR}:/media #optional
      - ${SERVER_DATA_DIR}/jellyfin/media2:/media2:ro

# Indexers

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
    <<: *environment
    <<: *policy
    <<: *security
    <<: *network 

    volumes:
      -  ${SERVER_DATA_DIR}/prowlarr/config:/config
    ports:
      - 7001:9696
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    <<: *environment 
    <<: *policy
    <<: *network 

    volumes:
      - ${SERVER_DATA_DIR}/transmission/config:/config
      - ${SERVER_STORAGE_DIR}/downloads:/downloads
      - ${SERVER_STORAGE_DIR}/watch:/watch
    ports:
      - 7003:9091
      - 51413:51413
      - 51413:51413/udp

  # flexget:
  #   image: wiserain/flexget
  #   container_name: flexget
  #   <<: *environment
  #   <<: *policy
  #   <<: *network 
  #   restart: on-failure:5
  #   ports :
  #     - 5050:5050
  #   environment:
  #     - FG_WEBUI_PASSWD=holiComoEstas
  #     - TORRENT_PLUGIN=transmission
  #   volumes:
  #     - ${SERVER_STORAGE_DIR}/downloads:/data
  #     # - ${SERVER_DATA_DIR}/flexget/config:/config
  #     - ${REPO_CONFIG_DIR}/assets/flexget:/config


# Utils

  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    <<: *environment 
    <<: *policy
    <<: *security
    <<: *network 
    ports:
      - 8001:80
    volumes:
      - ${SERVER_STORAGE_DIR}:/srv
      - ${REPO_CONFIG_DIR}/assets/settings.json:/config/settings.json
      - ${REPO_CONFIG_DIR}/assets/filebrowser.db:/database/filebrowser.db

  komga:
    image: gotson/komga
    container_name: komga
    <<: *environment
    <<: *policy
    <<: *security
    <<: *network


    volumes:
      - ${SERVER_DATA_DIR}/komga/config:/config
      - ${SERVER_STORAGE_DIR}:/data
      # - /etc/timezone:/etc/timezone

    ports:
      - 8002:8080
    # user: "1000:1000"

  calibre:
    image:  lscr.io/linuxserver/calibre:latest
    container_name: calibre
    <<: *environment 
    <<: *policy
    <<: *network 
    ports:
      - 8004:8080
      - 8008:8081

    volumes:
      - ${SERVER_DATA_DIR}/calibre/config:/config
      - ${SERVER_STORAGE_DIR}/mybooks:/books

  kuma:
    container_name: kuma
    image: louislam/uptime-kuma:1
    <<: *environment 
    <<: *policy 
    <<: *network 
    volumes:
      -  ${SERVER_DATA_DIR}/uptime-kuma/config:/app/data
    ports:
      - "8005:3001"
  
  # webtop:
  #   image: lscr.io/linuxserver/webtop:latest
  #   container_name: webtop
  #   <<: *environment 
  #   <<: *policy 
  #   volumes:
  #     - ${SERVER_DATA_DIR}/webtop/config:/config
  #   ports:
  #     - 8006:3000

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    <<: *environment 
    <<: *policy
    <<: *security
    <<: *network 
    volumes:
      - ${SERVER_DATA_DIR}/readarr/config:/config
      - ${SERVER_STORAGE_DIR}/books:/books
      - ${SERVER_STORAGE_DIR}/downloads:/downloads #optional
    ports:
      - 8007:8787


  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    <<: *environment 
    <<: *policy 
    <<: *network 
    volumes:
      - ${SERVER_DATA_DIR}/firefox/config:/config
      - ${SERVER_STORAGE_DIR}/downloads:/downloads #optional
    shm_size: "1gb"
    ports:
      - 8009:3000

# System

  whoami:
    image: containous/whoami:latest
    container_name: whoami
    <<: *user 
    <<: *environment 
    <<: *policy 
    <<: *network 
    ports:
      - 9001:80

  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    container_name: librespeed
    <<: *environment 
    <<: *policy 
    <<: *network 
    volumes:
      - ${SERVER_DATA_DIR}/librespeed/config:/config
    ports:
      - 9002:80

