version: "3.3"

x-user: &user
  user: 1000:1000 # default
 
x-environment: &environment
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Guayaquil

x-policy: &policy
  restart: unless-stopped

x-security: &security
  security_opt:
    - no-new-privileges:true

x-network: &network
  networks:
    - home-network

networks:
  home-network:
    driver: bridge
  my-network:

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    <<: [*environment,*policy]
    network_mode: 'host'
    ports:
      -  8096:8096/tcp
    volumes:
      - ${SERVER_DATA_DIR}/jellyfin/config:/config
      - ${SERVER_DATA_DIR}/jellyfin/cache:/cache
      - ${SERVER_STORAGE_DIR}:/media #optional
      - ${SERVER_DATA_DIR}/jellyfin/media2:/media2:ro
      - ${SERVER_STORAGE_DIR}/downloads:/downloads #optional

    labels:
      - homepage.group=Streaming
      - homepage.name=Watch
      - homepage.container=jellyfin
      - homepage.server=my-docker
      - homepage.description=Jellyfin
      - homepage.href=http://${IP_ADDRESS_G}:8096
      - com.centurylinklabs.watchtower.enable=true
