- Streaming:
    - radarr:
        href: http://inverse.local:6002
        container: radarr
        server: my-docker
        widget:
          type: radarr
          url: http://inverse.local:6002
          key: f93184e22792464c9c364f291e09f29c


    - sonarr:
        href: http://inverse.local:6003
        container: sonarr
        server: my-docker
        widget:
          type: sonarr
          url: http://inverse.local:6003
          key: a5d583908e6341c6b9015f1652b001c2


    - jellyfin:
        href: http://inverse.local:8096
        container: jellyfin
        server: my-docker
        widget:
            type: sonarr
            url: http://inverse.local:8096
            key: d195e389d696446e80cea6f6791df84a

    - Bazarr:
        href: http://inverse.local:6001
        container: bazarr
        server: my-docker
        widget:
            type: bazarr
            url: http://inverse.local:6001
            key: 8b2245311b106dc14859d2df4be7d78f

- System:

    - Whoami:
        href: http://inverse.local:9001
        container: whoami
        server: my-docker

    - Librespeed:
        href: http://inverse.local:9002
        container: librespeed
        server: my-docker

    - prowlarr:
        server: my-docker
        href: http://inverse.local:7001
        container: prowlarr

    - transmission:
        server: my-docker
        href: http://inverse.local:7003
        container: transmission

    - Firefox:
        href: http://inverse.local:8009
        container: firefox
        server: my-docker

    # - jdownloader:
    #     server: my-docker
    #     href: http://inverse.local:3129
    #     container: jdownloader-2


- Utils:
    - Files:
        href: http://inverse.local:8001
        container: filebrowser
        server: my-docker

    - Komga:
        href: http://inverse.local:8002
        server: my-docker
        container: komga

    - Calibre:
        href: http://inverse.local:8004
        container: calibre
        server: my-docker

    - Kuma:
        href: http://inverse.local:8005
        container: kuma
        server: my-docker

