---
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Settings
title: inverse.local
background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
backgroundOpacity: 0.2
favicon: /app/public/images/logo.png
theme: dark 
base: http://inverse.local
language: en
target: _blank
layout:
  Streaming:
    style: row
    columns: 4
  Media Management:
    style: row
    columns: 4
  Downloads:
    style: row
    columns: 4
  Utils:
    style: row
    columns: 4
  Admin:
    style: row
    columns: 4

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

