---
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Settings
title: inverse.local
background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
backgroundOpacity: 0.5
favicon: app/config/logo.png
theme: dark 
headerStyle: boxed
base: http://inverse.local
language: en
target: _blank
layout:
  Media:
    style: row
    columns: 3
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

